name: main

on:
  push:
    branches:
      - main

jobs:
  contributors:
    if: "${{ github.event.head_commit.message != 'build: contributors' }}"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - name: Setup PNPM
        uses: pnpm/action-setup@v6
      - name: Install
        run: pnpm install --dangerously-allow-all-builds
      - name: Contributors
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          pnpm contributors
      - name: Push changes
        run: |
          git push origin "HEAD:${GITHUB_REF_NAME}"

  release:
    if: |
      !startsWith(github.event.head_commit.message, 'chore(release):') &&
      !startsWith(github.event.head_commit.message, 'docs:') &&
      !startsWith(github.event.head_commit.message, 'ci:')
    needs: [contributors]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.15.0
          registry-url: https://registry.npmjs.org
      - name: Install npm CLI with staged publishing
        run: npm install --global npm@12.2.0
      - name: Setup PNPM
        uses: pnpm/action-setup@v6
      - name: Install
        run: pnpm install --dangerously-allow-all-builds
      - name: Test
        run: pnpm test
      - name: Type Check
        run: pnpm typecheck
      - name: Coverage
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: pnpm build
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git pull origin main
          pnpm release
